### ISSUE TITLE
Custom path of desktop file - should not be expanded in prime directory

### ISSUE THREAD

**Issue by koppor** [snapcore/snapcraft#1489]
I manually set the path for my desktop file:

```
apps:
   jabref:
     command: desktop-launch java -jar $SNAP/jar/JabRef-4.0-dev.jar
     plugs: [home, network-bind, x11]
     desktop: buildres/snapcraft/jabref.desktop
```

This leads to

    Skipping prime jabref (already ran)
    The path 'prime/buildres/snapcraft/jabref.desktop' set for 'desktop' in 'jabref' does not exist.

If I change the path to

         desktop: ../buildres/snapcraft/jabref.desktop

everything works fine. It IMHO used to work without `../` in older versions in Zetsy.

Version: `snapcraft (2.33+17.04)` run in latest Ubuntu Zetsy (see https://github.com/koppor/docker-snapcraft-java-de/blob/v1.3.0/Dockerfile).
