### ISSUE TITLE
lib* files in $SNAP/usr/lib/ links to /usr/lib/

### ISSUE THREAD

**Issue by wmmihaa** [snapcore/snapcraft#1605]
Some files, such as $SNAP/usr/lib/x86_64-linux-gnu/libm.so is refering to files in the **/usr/lib/x86_64-linux-gnu** directory. As these files are not accessible from the snap shell it generates exceptions.

We have been able to reproduce the issue following these steps
1. Create a simple snap using:
```
parts:
  node:
    plugin: nodejs
    node-engine: 7.10.0
    build-packages:
    - python2.7
    - build-essential
    stage-packages:
    - python2.7
    - build-essential
    node-packages: [node-gyp@latest]
environment:
    PATH: $PATH:$SNAP/usr/bin
    PYTHON: $SNAP/usr/bin/python2.7
    CPLUS_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
    C_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

``` 
2. Enter snap shell
3. Copy the addon hello-world from (https://nodejs.org/docs/latest-v7.x/api/addons.html) into our snap to our snap shell home directory
4. added an alias to node-gyp
```
alias node-gyp="$SNAP/bin/node /snap/[MYSNAP]/x1/lib/node_modules/node-gyp/bin/node-gyp.js"
```
5. From the _addon_ directory, run
```
node-gyp configure
node-gyp build
```

We get the error:
```
make: Entering directory '/root/snap/mysnap/x1/demo/build'
     SOLINK_MODULE(target) Release/obj.target/addon.node
/snap/mysnap/x1/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a
```

So we search the entire $SNAP structure for **libmvec_nonshared.a** and found it in **$SNAP/usr/lib/x86_64-linux-gnu/libm.so**

The content of the file looks like this:
```
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib/x86_64-linux-gnu/libm.so.6  AS_NEEDED ( /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a /lib/x86_64-linux-gnu/libmvec.so.1 ) )
```
As the path is not relative the snap (although included in the $SNAP/usr/lib/x86_64-linux-gnu folder), the snap can not access the file (the file is there but the snap is not granted privileges).
