### ISSUE TITLE
node-engine does not support NodeJS 8.X.X

### ISSUE THREAD

**Issue by arkuhn** [snapcore/snapcraft#2001]
#### Issue description
When declaring a node version 8.X.X, snapcraft builds fail with a variety of errors.

#### Steps to reproduce the issue

1.  Explicitly point 'node-engine' to 8.10.0
2. run 'snapcraft'

```
name: hello-node-snap
version: "1.0.2"
summary: A simple hello world command
description: hello world
confinement: strict

apps:
  hello-node-snap:
    command: bin/hello-node-snap
    plugs: [network]

parts:
  hello-node-snap:
    plugin: nodejs
    node-engine: 8.10.0
    node-packages:
      - hello-node-snap
```

#### What's the expected result?

I've received the following errors:
[Errno 2] No such file or directory: mysnapdirectory/prime/bin/hello-node-snap
OSError: [Errno 26] Text file busy: mysnapdirectory/parts/hello-node-snap/install/bin/node

#### Additional details

It looks as if npm is creating a package.json lockfile and silently failing.
 

#### Bug report
https://bugs.launchpad.net/snapcraft/+bug/1755524
