### ISSUE TITLE
Some stage packages don't have their dependencies fullfilled

### ISSUE THREAD

**Issue by sergio-costas** [snapcore/snapcraft#4232]
### Bug Description

In some cases, installing a stage package doesn't install the needed dependencies. Specifically, this happens (at least) with `python3-setuptools`, which requires (it can't work without it) and has in its dependency list, the package `python3-pkg-resources`.

```
$ apt show python3-setuptools
Package: python3-setuptools
Version: 66.1.1-1
Priority: optional
Section: python
Source: setuptools
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2.594 kB
Depends: python3-pkg-resources (= 66.1.1-1), python3-distutils, python3:any
Suggests: python-setuptools-doc
Homepage: https://pypi.python.org/pypi/setuptools
Task: server-minimal, cloud-image, ubuntustudio-photography, ubuntustudio-publishing, edubuntu-desktop-gnome
Download-Size: 453 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu lunar/main amd64 Packages
Description: Python3 Distutils Enhancements
 Extensión de python-distutils para distribuciones grandes o complejas.
 ```

### To Reproduce

Just create this snap:

```
name: snap-deb-test
base: core22
version: '0.1'
summary: Test of .deb dependencies
description: |
  A test snap to see if the dependencies of a .deb in stage-packages are
  correctly installed or not.

grade: stable
confinement: strict

parts:
  my-part:
    plugin: nil
    stage-packages:
      - python3-setuptools # it should also install python3-pkg-resources... but it doesn't
```

decompress it with `unsquashfs snap-deb-test_0.1_amd64.snap`, and go to `squashfs-root/usr/lib/python3/dist-packages`: there will be the `setuptools` and `setuptools-59.6.0.egg-info` folders, but not the ones for `pkg-resources`.

### Environment

I'm using LXD.

### snapcraft.yaml

```shell
name: snap-deb-test
base: core22
version: '0.1'
summary: Test of .deb dependencies
description: |
  A test snap to see if the dependencies of a .deb in stage-packages are
  correctly installed or not.

grade: stable
confinement: strict

parts:
  my-part:
    plugin: nil
    stage-packages:
      - python3-setuptools # it should also install python3-pkg-resources... but it doesn't
```

### Relevant log output

```shell
Nothing special, the snap as-is builds without errors.
```

### Additional context

Tested both with Core20 and Core22. It fails in both cases.

Also tested adding `gedit` to the list. It does install dependencies like Gtk and others.

Crazy suggestion: Maybe the problem is that the code detects that `python3-pkg-resources` is installed system-wide, and that makes it think that it must not be downloaded for the `stage`? (when it should only affect to `build-packages`, never to `stage-packages`, where everything should be downloaded).
