### ISSUE TITLE
snapcraft configure hook fails: segmentation fault

### ISSUE THREAD

**Issue by barrettj12** [snapcore/snapcraft#4440]
### Bug Description

When installing the `snapcraft` snap on an AWS arm64 GitHub runner, the "configure" hook fails
```
error: cannot perform the following tasks:
- Run configure hook of "snapcraft" snap if present (run hook "configure": signal: segmentation fault)
```

### To Reproduce

Run the following GitHub workflow:
```yaml
jobs:
  snap:
    name: linux-arm64
    runs-on: [self-hosted, linux, arm64, aws, large]
    steps:
    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install snapcraft --classic
```

### Environment

Distribution: Ubuntu 22.04.3 LTS
  Architecture: aarch64
  
  on AWS

### snapcraft.yaml

```shell
N/A
```

### Relevant log output

```shell
+ sudo snap install snapcraft --classic
error: cannot perform the following tasks:
- Run configure hook of "snapcraft" snap if present (run hook "configure": signal: segmentation fault)
```

### Additional context

Run here: https://github.com/juju/juju/actions/runs/6783177627/job/18436880350?pr=16548
