### ISSUE TITLE
Generate metadata for components

### ISSUE THREAD

**Issue by mr-cal** [snapcore/snapcraft#4466]
### What needs to get done

As a post-prime step, snapcraft should generate a `meta/component.yaml` metadata file for each component.

`component.yaml` files should contain the following, collected from the definition in `snapcraft.yaml`:
```yaml
component: <snap name>+<component name>
type: test
summary: ...
description: ...
version: ... # optional
```

### Why it needs to get done

To support components in snapcraft
