### ISSUE TITLE
`primed-stage-packages` isn't in manifest.yaml when using override-prime

### ISSUE THREAD

**Issue by mr-cal** [snapcore/snapcraft#5552]
### Bug Description

When using `override-prime`, the `primed-stage-packages` entry in the `manifest.yaml` is never populated.

This is due to an upstream issue in craft-parts (https://github.com/canonical/craft-parts/issues/1122).

We've worked around this problem before by warning when `override-prime` is used (https://github.com/canonical/snapcraft/issues/4547).

### To Reproduce

Build the snap below with `SNAPCRAFT_BUILD_INFO=y snapcraft` and inspect the manifest with and without the `override-prime` keyword.

### Environment

Snapcraft 8.9.0
This affects core22+ since this is a craft-parts issue.

### snapcraft.yaml

```yaml
name: my-snap-test
version: '0.1'
summary: A test snap to demonstrate primed-stage-packages
description: |
  This is a simple snap to show how stage-packages are primed.
 
grade: stable
confinement: strict
base: core22
 
parts:
  my-part:
    plugin: nil
    stage-packages:
      - curl
    override-prime: |
      craftctl default
```

### Relevant log output

```shell
n/a
```
